# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxbsP8Mk3Px0Bq6YAgSOyWF6Ce03SSWn
"""

import contador

def main():
    """
    Función principal que solicita al usuario un número entero positivo
    e inicia la cuenta regresiva recursiva.
    """
    while True:
        try:
            numero = int(input("Ingrese un número entero positivo: "))
            if numero >= 0:
                break
            else:
                print("El número debe ser positivo. Intenta de nuevo.")
        except ValueError:
            print("Entrada inválida. Por favor, ingrese un número entero.")

    print("\n Iniciando cuenta regresiva...\n")
    contador.cuenta_regresiva(numero)

if __name__ == "__main__":
    main()